### ISSUE TITLE
Blogs /news items not showing up in google

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#180] opened 2016-12-19 11:03 UTC
Even though we have better metadata than the original blogs we are cross-posting, they are not showing up in google results. There must be something wrong with they way our website is being crawled (or not) by google.

For example, try a google search for this blog, which has been on the Land Portal for five weeks: 

Toward a Carbon-Neutral Future: Why Land and Resource Rights Matter

http://blogs.ei.columbia.edu/2016/10/27/towards-a-carbon-neutral-future-why-land-and-resource-rights-matter/

https://landportal.info/blog-post/2016/11/toward-carbon-neutral-future-why-land-and-resource-rights-matter

The Land Portal version doesn't come up at all after page after page of google search results, which is a serious problem. It should be in the second position, as we are the only ones who appear to have cross-posted the blog. This is a problem for this blog, but is no doubt a larger issue inhibiting the Land Portal from getting visits when people search for information.

**Comment by realneilsorensen** [comment] 2017-01-06 10:21
This is a clear example that there is a major problem. Normally this blog should be second in the results when searching for the title. There is no reason why it wouldn't show up if our metadata, titles, etc. were being crawled correctly.

**Comment by jcr** [comment] 2017-01-06 10:35
this is a duplicate of #191

**Closed by jcr** 2017-01-06 10:35 UTC
Labels: bug, help wanted

**Comment by realneilsorensen** [comment] 2017-01-06 10:47
This is a separate issue, a separate blog. Perhaps related. This is the original and more detailed issue comment. I don't see the point in closing comments all the time for issues that haven't been dealt with.
