### ISSUE TITLE
Promoting to country pages not working

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#241] opened 2017-01-30 16:17 UTC
The promotion to country pages button is not working, at least for events, maybe for other pages. It blinks on an off and I can't put  in the country name.

**Comment by jcr** [comment] 2017-01-31 07:46
I cannot reproduce this. The select have been changed to the 'tag'-like one last week.
By " It blinks on an off and I can't put in the country name " I guess you're talking about the select in the "Publishing options", once you checked "Promoted to country page", right?

What browser were you using when that occur? could you try with another one?

**Comment by jcr** [comment] 2017-02-15 19:39
In agreement with Laura the promoted content on the Country page is now showing all content tagged with the given country.
 1/ it show stuff promoted to a country page
 2/ it show the most recent items to have as much as 4 total.

The field should be clean up in the landportal_promoted module to close this ticket

**Closed** 2017-02-21 13:07 UTC
Labels: cleanup
