### ISSUE TITLE
Sitemap XML

### ISSUE THREAD

**Issue by lmeggiolaro** [landportal/drupal#77] opened 2016-05-27 08:00 UTC
I was just trying to look at the sitemap xml on Drupal. It doesn’t appear to be a file I can download, and I can’t tell if it is functioning. Also, there is no French, Spanish or Portuguese xml sitemap. Consequently, I am wondering how search engines can be picking up our information. If our development team could look at this, I would think it would be relatively urgent to address.

**Comment by jcr** [comment] 2016-07-14 03:37
This is working as designed. the sitemap files https://landportal.info/sitemap.xml?page=1 and https://landportal.info/sitemap.xml?page=2 are technically correct but not meant to be handled / looked at by hand.

This is something I added end of last year (there was no optimization or simply anything) to help search engines index the new site better.
We (I) am periodically reviewing various parameters and indicators to have the basic working so the site can be indexed.

I am closing this right now as this work as intended.

**Closed by jcr** 2016-07-14 03:37 UTC
Labels: wontfix
