### ISSUE TITLE
Pictures on profiles not resizing

### ISSUE THREAD

**Issue by realneilsorensen** [landportal/drupal#171] opened 2016-11-25 14:50 UTC
I've flagged this problem before on Laura's account a few months ago. Pictures on individual profiles are no longer resized and now appear huge below the profile in random sizes, which looks terrible and not at all professional.

**Comment by jcr** [comment] 2016-11-29 10:20
.In the next release the profile page will be cleaned up and re-worked a bit.
Maybe you could help make it better by providing useful feedback or creating a short mockup on how you would make those page look good.
I will let you know as soon as I work on the next version user pages (I actually already started to look at the whole user process... ), this is one of the last part in the new version that will need some -consequent- work to look good and actually be nice.

Generally speaking the current UX for registering / login, viewing and updating users account or profile is just horrible (not only the user page) from A-Z - and was aside of the picture issue- pretty much always like that on the new site.
This is exactly why, rather than spending an awful lot of time fixing specifics, this is done directly by (re)using/implementing a proper theme that isn't full of hacks and in many case get back to more basics / standard Drupal functionality, which actually provide better UX and UI.

**Comment by jcr** [comment] 2016-12-01 15:21
closing this one as a duplicate of https://github.com/landportal/drupal/issues/88
on the live site I have limited the size on user's page to 220x220 so it look a bit less horrible.

I will be working next week on the user (and organization) part for the new theme.

**Closed by jcr** 2016-12-01 15:21 UTC
